package edu.training.web.controller.concrete;

public enum CommandName {

	DO_LOG_IN, DO_LOG_OUT, DO_REGISTRATION, DO_DELETE_USER, DO_PROFILE_UPDATE,

	GO_TO_ADMIN_PAGE, GO_TO_IN_PROCESS_PAGE, GO_TO_LOG_IN_PAGE, GO_TO_MAIN_PAGE, GO_TO_PROFILE_PAGE,
	GO_TO_REGISTRATION_PAGE, GO_TO_START_PAGE,

	NO_SUCH_COMMAND

}
